### ISSUE TITLE
Future Plans

### ISSUE THREAD

**Issue by nicdgonzalez** [nicdgonzalez/clap#1]
# Overview

Use tasks to track what needs to be done on this project.

# Intended outcome

To make progress towards the first production ready release (version 1.0.0).

# Tasks

- [x] Add support for simple scripts.
- [ ] Add tests
    - [ ] Lexer
    - [ ] Parser
    - [ ] Type Converter
- [ ] Add documentation
- [ ] Generate documentation using Sphinx
- [ ] Complete demo project [Fuji](https://github.com/nicdgonzalez/fuji)
- [x] Create examples
- [x] Update `Extension` logic in `ArgumentParser`
    - [x] Rename `.add_extension` to `.extend`
    - [x] Separate `Extension` logic from `.add_command` into `.add_extension`
- [x] mypy should pass tests with no errors while running with `--strict`.
- [ ] Maybe create Builders for the parameter objects?
- [x] Clean up TODOs/comments
- [ ] A better options tree in generated help menu
    - [ ] Add optional escapes `[--]` in the usage section
    - [ ] Add conflicts/requires
- [ ] Update ABCs
    - [ ] Combine `HasOptions` and `CallableArgument`
    - [ ] Double check attributes/methods to make sure everything is accurate

# Future Plans

- [ ] Release v1.0.0
